### ISSUE TITLE
Aus Liste von Opcodes Classfile erstellen

### ISSUE THREAD

**Issue by Ironeer** [cmjava2023/compiler#38]

**Comment by Ironeer** [comment]
#39 habe ich fertig, damit das ganze wieder funktioniert fehlt aber dieses Issue. Deshalb sollte das issue auf dem gleichen Branch  ( bytecode/opcodes_with_constantpoolitems ) gemacht werden und erst dann gemerged werden. Ich habe für dieses Issue hier ein TODO in den Code gepackt. Wir können wenn du willst aber auch gerne um 17 Uhr vor dem Edmonton Meeting zusammen schauen, so ganz final sind unsere Überlegungen glaube ich noch nicht.

**Comment by Sascha-Ruehrup** [comment]
Es müssen dann aus dem AST anhand der Nodes die Liste der Opcodes erstellt werden und dann die Liste jeweils mit Opcode.toByte() zu den methodInfo-Bytes des Datamodels hinzugefügt werden, richtig?

Ja 17 Uhr treffen wäre gut.

**Comment by Ironeer** [comment]
Aus dem AST eine Liste von Opcodes zu erstellen hatten wir als #37 abgespaltet. Für die Helloworld Sachen habe ich unsere Hardcodierung auf das Format angepasst. In der Task hier müsste "nur" eine vorhandenen Liste von Opcodes in Bytes der MethodInfo umgewandelt werden. Manche Opcodes enthalten jetzt ConstantInfos wie zum Beispiel StringConstantInfo. Diese müssen auf den Constantpool gelegt werden und in die MethodInfobytes wandert der Index.

Aber lass uns dann um 17 Uhr gucken
