### ISSUE TITLE
Fix Test cases or Github CI Pipeline

### ISSUE THREAD

**Issue by JonaZz747** [cmjava2023/compiler#49]
All builds are failing since #46 due to test assert errors in latest pull.

Is this a pipeline error? A error of the test cases? Or, is our code incorrect?

Best option would be to mark all test cases that are expected to fail due to unfinished implementations as such, so the pipeline runs correctly and only fails if there is a real  bug in our code...

We want main's CI to always succeed, don't we?

**Comment by Ironeer** [comment]
It is not a pipeline error. The tests were created for the Parser and we are waiting that the group fixes the errors and updates the tests. But you are right, it is a bad thing that they ended up on the master branch, which was a branching mistake we did.

I disabled the failing tests in #50 and created the issue #51 for the Parser group to fix and enable them
