### ISSUE TITLE
Consider supporting Type Casting because VM group included it in the primitive milestone

### ISSUE THREAD

**Issue by Ironeer** [cmjava2023/compiler#53]
Lexer Parser already fixed the test primitive/doubles/conversions. Unfortunately [the test file (copied from the VM Group)
uses type casting](https://github.com/cmjava2023/compiler/blob/35cb95873e36d460d27552e86e41ec0f16474a9c/src/test/resources/java-test-files/cmjava2023/primitive/doubles/conversions/Main.java#L7).

The ast only contains null for the value of these assignments as you can see in the [ASTTest we created to have a look what we get out of the ast](https://github.com/cmjava2023/compiler/blob/35cb95873e36d460d27552e86e41ec0f16474a9c/src/test/resources/java-test-files/cmjava2023/primitive/doubles/conversions/AST.txt#L43).

You can work on this issue on the branch [ast/support_type_casting](https://github.com/cmjava2023/compiler/tree/ast/support_type_casting) where we created the test on

**Comment by Jerbrich** [comment]
@SebastianSossna Can you look into that ? You might have more experience with the expressions.

**Comment by Ironeer** [comment]
this needs to be finished before #72 can be done

**Comment by Jerbrich** [comment]
Will be done with #75
