### ISSUE TITLE
Put symbols on ASTNodes with identifiers + undeclared variables and functions

### ISSUE THREAD

**Issue by Ironeer** [cmjava2023/compiler#61]
We have to resolve the used identifiers while traversing the AST. We need a Scope to resolve identifiers. Not all ASTNodes have a reference to a scope (for instance the variableAssignment has no scope to resolve the Variable Names in).

We think a solution would be to put the current-scope on every ASTNode that has values that can be resolved

**Comment by Jerbrich** [comment]
@Ironeer When I am checking for undeclared variables, functions and so on I will be resolving them. Would it be better for you to get the reference to the symbol in the node instead of the scope?.

**Comment by Ironeer** [comment]
@Jerbrich that would be perfect and more efficient
