### ISSUE TITLE
Adjusting the expected output files as of #68

### ISSUE THREAD

**Issue by SebastianSossna** [cmjava2023/compiler#69]
The expected output files of the ast parse tree need to be adjusted.

Please view & confirm #68 first.

**Comment by Ironeer** [comment]
I adjusted it in #68 , I think in general it would be easier that you change the AST.txt when you are satisfied with the actual ast. If you request a review we can see the changed AST directly in the pull request and can give you better feedback. Also a pull request should aim to have all tests passed before the merge so your Pull requests should also adjust the tests. 

You can run the tests here:
![grafik](https://github.com/cmjava2023/compiler/assets/19492236/1652fafc-8ebe-46d5-b9f6-938f1a8ccfb4)

And then see the results and click "<Click to see difference>" to open a nice diff view.
![grafik](https://github.com/cmjava2023/compiler/assets/19492236/d7bc6376-b084-46b8-9f64-19b3b28bb1cd)

If the actual ast on the right suits you, copy it and insert it into the AST.txt
