### ISSUE TITLE
resolve all constant pool indices in test in HexClassFileTester.parseConstantPool

### ISSUE THREAD

**Issue by Ironeer** [cmjava2023/compiler#97]

**Comment by Sascha-Ruehrup** [comment]
hey, hab ich den Issue richtig verstanden, dass aus unresolvedConstantPool z.B. "0C 0009.000A" ersetzt werden soll durch "java/lang/System.out:Ljava/io/PrintStream;" und dann die aufgelösten Werte alle wie vorher in constantPoolItems geschrieben werden?

ein Test schlägt fehl, weil der noch =C 0009.000A erwartet.

**Comment by Ironeer** [comment]
Genau, das ist gemeint. Gut wäre denke ich auch noch, wenn der ConstantInfo-Typ noch vor den Daten steht, damit man weiß was die Daten bedeuten.

Die Erwartung der Tests musst du dann an die neue Ausgabe anpassen.

**Comment by Sascha-Ruehrup** [comment]
ConstantInfo-Typ wird jetzt davorgesetzt: 'Fieldref java/lang/System.out:Ljava/io/PrintStream;'
Die ClassfileContent.json hab ich entsprechend des tatsächlichen output angepasst.

**Comment by Ironeer** [comment]
Sehr cool, danke dir. Dann bring es gerne über einen Pull-Request in den Master
